Repository PTechKTW2023/PTECHKTW, pull requests merged in 2025-07, with the labels that each got.

#88 Add a chat placeholder
  Booker/Pages/Chat.cshtml
  Booker/Pages/Index.cshtml
  Booker/Pages/Shared/_LoginPartial.cshtml
Labels: enhancement

#90 Add logo and favicons
  Booker/Pages/Shared/_Layout.cshtml
  Booker/wwwroot/favicon.ico
  Booker/wwwroot/favicons/apple-touch-icon.png
  Booker/wwwroot/favicons/favicon-96x96.png
  Booker/wwwroot/favicons/favicon.ico
  Booker/wwwroot/favicons/favicon.svg
  Booker/wwwroot/favicons/site.webmanifest
  Booker/wwwroot/favicons/web-app-manifest-192x192.png
  Booker/wwwroot/favicons/web-app-manifest-512x512.png
  Booker/wwwroot/img/logo-text.svg
  Booker/wwwroot/scss/_hamburger.scss
Labels: enhancement

#92 Fix translations & translate error page
  Booker/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
  Booker/Areas/Identity/Pages/Account/Login.cshtml.cs
  Booker/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml.cs
  Booker/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml.cs
  Booker/Areas/Identity/Pages/Account/Manage/Email.cshtml.cs
  Booker/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  Booker/Areas/Identity/Pages/Account/Register.cshtml.cs
  Booker/Areas/Identity/Pages/Account/ResendEmailConfirmation.cshtml.cs
  Booker/Areas/Identity/Pages/Account/ResetPassword.cshtml.cs
  Booker/Areas/Identity/Utilities/ErrorDescriber.cs
  Booker/Pages/Error.cshtml
  Booker/Program.cs
  Booker/Resources/DataAnnotations.cs
  Booker/Resources/DataAnnotations.resx
  Booker/Services/ResourceManagerHack.cs
Labels: bug, enhancement

#94 Fix hamburger menu breakpoint and background
  Booker/wwwroot/scss/_hamburger.scss
Labels: bug

#86 Implementation of the sales ad editing form
  Booker/Areas/Identity/Pages/Account/Manage/Email.cshtml
  Booker/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
  Booker/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  Booker/Pages/Add.cshtml.cs
  Booker/Pages/Book.cshtml
  Booker/Pages/Book.cshtml.cs
  Booker/Pages/Edit.cshtml
  Booker/Pages/Edit.cshtml.cs
  Booker/Pages/Index.cshtml
  Booker/Pages/Index.cshtml.cs
  Booker/Pages/Profile/Favorites.cshtml.cs
  Booker/Pages/Profile/Index.cshtml.cs
  Booker/Pages/_BookTile.cshtml
  Booker/Pages/_ItemGallery.cshtml
  Booker/wwwroot/js/site.js
  Booker/wwwroot/scss/_book.scss
  Booker/wwwroot/scss/_index.scss
Labels: enhancement

#95 Hotfix for transparent menu
  Booker/wwwroot/scss/_hamburger.scss
Labels: bug

#100 Hotfix duplicate emails
  Booker/Program.cs
Labels: bug

#101 Hotfix JavaScript errors
  Booker/wwwroot/js/site.js
Labels: bug
